/**
 * import-people.ts — one-off importer that scaffolds sourced, review-flagged
 * profile stubs for recognizable PUBLIC FIGURES who are documented as named in
 * the Epstein files but were missing from the database.
 *
 * SAFETY: curated by hand from authoritative public lists (Wikipedia's master
 * list, DOJ letter coverage, major outlets). Every entry is a public figure
 * with a DOCUMENTED connection (emails, flight logs, meetings, funding). NO
 * victims/survivors/minors, no recruitment-adjacent figures, no private
 * individuals, no "merely referenced" names. Content is neutral and sourced;
 * profiles are status:'review' + autogenerated:true and carry the inclusion
 * disclaimer (rendered by PersonLayout). Idempotent: never overwrites.
 */
import { writeFileSync, existsSync, readdirSync, readFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import { slugify, parseFrontmatter } from './lib/pipeline-utils.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const PEOPLE_DIR = join(__dirname, '..', 'src', 'content', 'people');

const WIKI = {
  title: 'List of people named in the Epstein files — Wikipedia',
  url: 'https://en.wikipedia.org/wiki/List_of_people_named_in_the_Epstein_files',
};

type Cat = 'named-in-documents' | 'official' | 'associate' | 'legal' | 'witness' | 'other';
interface Person {
  name: string;
  aka?: string[];
  role: string;
  category: Cat;
  context: string; // neutral, factual, how/where named
  sources?: { title: string; url: string }[]; // WIKI added automatically
}

// ── Curated public figures (documented connection; victims/obscure/merely-referenced excluded) ──
const PEOPLE: Person[] = [
  // Politicians / officials
  { name: 'Ehud Barak', role: 'Former Prime Minister of Israel', category: 'official', context: 'Documented in released emails and meeting records detailing years of correspondence and visits with Epstein; Barak says he witnessed no wrongdoing and regrets the association.', sources: [{ title: 'Israel’s Barak says he regrets knowing Epstein (NBC News)', url: 'https://www.nbcnews.com/world/israel/israels-barak-says-regrets-knowing-epstein-documents-detail-long-frien-rcna259004' }] },
  { name: 'Robert F. Kennedy Jr.', aka: ['RFK Jr.'], role: 'U.S. Secretary of Health and Human Services', category: 'official', context: 'Recorded on Epstein flight logs and in a contact book; has acknowledged taking flights in the 1990s and is not accused of wrongdoing.', sources: [{ title: 'RFK Jr. says he took two plane rides with Epstein (NewsNation)', url: 'https://www.newsnationnow.com/danabramslive/rfk-jr-kennedy-plane-rides-jeffrey-epstein/' }] },
  { name: 'William Burns', role: 'CIA Director; former Deputy Secretary of State', category: 'official', context: 'Scheduling documents in the files reference meetings with Epstein in 2014, including at his Manhattan townhouse.' },
  { name: 'Kevin Rudd', role: 'Former Prime Minister of Australia', category: 'official', context: 'Documents reference a 2015 meeting with Epstein; Rudd has said it concerned a think-tank matter.' },
  { name: 'Bill Richardson', role: 'Former Governor of New Mexico (deceased)', category: 'official', context: 'Records indicate he arranged to meet Epstein several times; named in unsealed court documents. No charges were brought.' },
  { name: 'Stacey Plaskett', role: 'U.S. Delegate for the U.S. Virgin Islands', category: 'official', context: 'Text messages in the files show an exchange with Epstein; she has said she did nothing improper.' },
  { name: 'Hardeep Singh Puri', role: 'Indian Union Minister', category: 'official', context: 'Named in a November 2014 email to Epstein, which he has acknowledged.' },
  { name: 'Andrés Pastrana', aka: ['Andrés Pastrana Arango'], role: 'Former President of Colombia', category: 'official', context: 'Recorded in 2003 flight logs of Epstein’s aircraft; acknowledged a stop-over trip.' },
  { name: 'Børge Brende', role: 'President of the World Economic Forum; former Norwegian foreign minister', category: 'official', context: 'Files document 120+ emails and texts with Epstein and attendance at New York dinners.' },
  { name: 'Mette-Marit', aka: ['Crown Princess Mette-Marit of Norway'], role: 'Crown Princess of Norway', category: 'official', context: 'Referenced over a thousand times in the files (2011–2014), including email contact with Epstein.' },
  { name: 'Princess Sofia of Sweden', aka: ['Princess Sofia, Duchess of Värmland'], role: 'Member of the Swedish royal family', category: 'official', context: 'Files indicate she met Epstein a few times in New York in 2005, before joining the royal family.' },
  { name: 'Karim Wade', role: 'Senegalese politician', category: 'official', context: 'Emails indicate Epstein assisted him with legal and lobbying matters.' },
  { name: 'Robert Mugabe', role: 'Former President of Zimbabwe (deceased)', category: 'official', context: 'Named in a 2015 email exchange and a 2017 FBI record within the released materials.' },
  { name: 'John Phelan', role: 'U.S. Secretary of the Navy', category: 'official', context: 'Named on a 2006 flight manifest from Epstein’s private plane.' },
  { name: 'Mehmet Oz', aka: ['Dr. Oz'], role: 'CMS Administrator; television physician', category: 'official', context: 'Files reference travel expenses paid by Epstein in 2004 and a 2014 event invitation.' },
  { name: 'Kimbal Musk', role: 'Businessman and restaurateur', category: 'associate', context: 'Named over 140 times in emails; reportedly socialized with Epstein beginning in 2012.' },
  { name: 'John de Jongh Jr.', role: 'Former Governor of the U.S. Virgin Islands', category: 'official', context: 'Emails in the files show Epstein paid his children’s college tuition (2008–2009).' },
  { name: 'Albert Bryan Jr.', role: 'Governor of the U.S. Virgin Islands', category: 'official', context: 'Named in correspondence concerning Epstein contacting him about land clearing.' },
  { name: 'Kenneth Mapp', role: 'Former Governor of the U.S. Virgin Islands', category: 'official', context: 'A 2016 email references a loan request and private meetings with Epstein.' },
  { name: 'Gary King', role: 'Former Attorney General of New Mexico', category: 'official', context: 'Files reference Epstein campaign donations and private-jet travel from the early 1990s to 2014.' },
  { name: 'Vitaly Churkin', role: 'Former Russian Permanent Representative to the UN (deceased)', category: 'official', context: 'Named in Epstein dinner schedules and email communications.' },

  // Business / finance / tech
  { name: 'Elon Musk', role: 'CEO of Tesla and SpaceX; owner of X', category: 'named-in-documents', context: 'Emails and calendars in the released documents reference coordinating a possible island visit and dinners; Musk disputes that any visit occurred.', sources: [{ title: 'A list of powerful men named in the Epstein files (PBS)', url: 'https://www.pbs.org/newshour/nation/a-list-of-powerful-men-named-in-the-epstein-files-from-elon-musk-to-former-prince-andrew' }] },
  { name: 'Mark Zuckerberg', role: 'Co-founder and CEO of Meta', category: 'named-in-documents', context: 'An Epstein email describes a 2015 dinner reportedly attended by Zuckerberg; later emails reference contact.' },
  { name: 'Sergey Brin', role: 'Co-founder of Google', category: 'associate', context: '2003 emails reference plans to meet Epstein and Maxwell; documents indicate an island visit.', sources: [{ title: 'A list of powerful men named in the Epstein files (PBS)', url: 'https://www.pbs.org/newshour/nation/a-list-of-powerful-men-named-in-the-epstein-files-from-elon-musk-to-former-prince-andrew' }] },
  { name: 'Reid Hoffman', role: 'Co-founder of LinkedIn; investor', category: 'associate', context: 'Documents show a 2014 island visit, a 2015 dinner, and email and Skype contact with Epstein.' },
  { name: 'Mortimer Zuckerman', aka: ['Mort Zuckerman'], role: 'Billionaire media owner (New York Daily News, U.S. News)', category: 'associate', context: 'Files document a long relationship with Epstein, including his 2003 birthday book and Epstein’s efforts to influence coverage.', sources: [{ title: 'Epstein pressed billionaire media mogul to influence coverage (Al Jazeera)', url: 'https://www.aljazeera.com/news/2026/2/9/epstein-pressed-billionaire-media-mogul-to-influence-coverage-files-reveal' }] },
  { name: 'Carl Icahn', role: 'Billionaire investor', category: 'named-in-documents', context: 'Reported to appear in a mid-1990s version of Epstein’s address book; inclusion is not evidence of wrongdoing.', sources: [{ title: 'Epstein’s little black book auction (Scripps News)', url: 'https://www.scrippsnews.com/us-news/jeffrey-epsteins-little-black-book-just-went-up-for-auction-heres-whose-names-are-listed-in-it' }] },
  { name: 'Leonard Blavatnik', role: 'British-American billionaire businessman', category: 'associate', context: 'Files show correspondence with Epstein and invitations to gatherings.' },
  { name: 'Todd Boehly', role: 'Chairman of Chelsea F.C.; Guggenheim partner', category: 'associate', context: '2011 emails in the files arrange meetings with Epstein.' },
  { name: 'Josh Harris', role: 'Co-founder of Apollo Global Management; sports-team owner', category: 'associate', context: 'Files show email exchanges (2013–2016) and a 2014 meeting with Epstein.' },
  { name: 'Ron Baron', role: 'Investor; founder of Baron Capital', category: 'associate', context: 'Files reference attendance at a 2014 dinner at Epstein’s New York home.' },
  { name: 'Andrew Farkas', role: 'Real-estate and marina investor', category: 'associate', context: 'Co-owned a St. Thomas marina with Epstein; exchanged emails and stayed on his island.' },
  { name: 'Gordon Getty', role: 'Businessman and composer; Getty Oil heir', category: 'associate', context: 'Corresponded with and spent time with Epstein (2013–2018) after an introduction.' },
  { name: 'Ronald Lauder', role: 'Billionaire businessman (Estée Lauder heir)', category: 'associate', context: 'Appears in the files over 900 times; in 2014 Epstein set up an LLC connected to an art purchase.' },
  { name: 'Marc Rowan', role: 'CEO of Apollo Global Management', category: 'associate', context: 'Files show correspondence with Epstein regarding tax matters.' },
  { name: 'Bobby Kotick', role: 'Former CEO of Activision Blizzard', category: 'associate', context: 'Emails show Epstein invited him to events and consulted him.' },
  { name: 'Jes Staley', aka: ['James Staley'], role: 'Former CEO of Barclays; former JPMorgan executive', category: 'named-in-documents', context: 'More than 1,200 emails and contacts between Staley and Epstein were uncovered by JPMorgan Chase and provided to the UK FCA. Staley described Epstein as one of his "deepest" and "most cherished" friends but misled regulators about the nature of the relationship; the UK Upper Tribunal upheld a lifetime FCA ban and £1.1 million fine against Staley in June 2025.', sources: [{ title: 'Upper Tribunal upholds Jes Staley ban (FCA)', url: 'https://www.fca.org.uk/news/press-releases/upper-tribunal-upholds-jes-staley-ban' }, { title: 'Jes Staley and Jeffrey Epstein: Evidence That Doomed Ex-Barclays CEO Career (Bloomberg)', url: 'https://www.bloomberg.com/features/2025-jes-staley-jeffrey-epstein-fca/' }] },
  { name: 'Nathan Myhrvold', role: 'Former Microsoft CTO; inventor', category: 'associate', context: 'Emailed and met Epstein regularly (2010–2018), visited his properties, and contributed to a birthday book.' },
  { name: 'Doug Band', role: 'Former adviser to Bill Clinton', category: 'associate', context: 'Named in emails and flight records; reportedly flew on Epstein’s jet over 35 times.' },
  { name: 'Anil Ambani', role: 'Indian billionaire businessman', category: 'named-in-documents', context: 'Named in Epstein’s messages; reportedly introduced through an associate.' },
  { name: 'Flavio Briatore', role: 'Italian businessman; former Formula One manager', category: 'associate', context: 'Maintained email contact with Epstein.' },
  { name: 'Jean Pigozzi', role: 'Businessman, art collector and photographer', category: 'associate', context: 'Files show substantial correspondence with Epstein.' },
  { name: 'Nick Candy', role: 'British luxury property developer', category: 'named-in-documents', context: 'Named in dozens of files; reportedly interacted with Epstein associates.' },
  { name: 'Brock Pierce', role: 'Cryptocurrency entrepreneur; Tether co-founder', category: 'associate', context: 'Reportedly first met Epstein at a 2011 conference on Little Saint James.' },
  { name: 'Nicole Junkermann', role: 'German businesswoman and investor', category: 'associate', context: 'Documents show email correspondence and a friendship with Epstein.' },
  { name: 'Lynn Forester de Rothschild', role: 'Businesswoman; Lady de Rothschild', category: 'associate', context: 'Named in files and reporting in connection with introductions within Epstein’s social circle.' },
  { name: 'Ariane de Rothschild', role: 'Banking executive (Edmond de Rothschild Group)', category: 'associate', context: 'Scheduling documents show more than a dozen meetings (2013 onward).' },
  { name: 'Jean Todt', role: 'Former president of the FIA; motorsport executive', category: 'associate', context: 'Files indicate a 2017 visit to Epstein’s home after an introduction.' },
  { name: 'Boris Nikolic', role: 'Biotech investor; former Gates Foundation science adviser', category: 'associate', context: 'Corresponded with Epstein, who named him a backup executor of his estate; Nikolic said he never agreed to the role.' },
  { name: 'Christopher Poole', aka: ['moot'], role: 'Founder of 4chan', category: 'named-in-documents', context: 'Files indicate Epstein met him in 2011 and described him favorably.' },

  // Academics / scientists
  { name: 'Joi Ito', aka: ['Joichi Ito'], role: 'Former Director of MIT Media Lab', category: 'named-in-documents', context: 'Accepted $525,000 for MIT Media Lab and $1.2 million for personal ventures from Epstein, directing staff to label Epstein an "anonymous" donor. Resigned as MIT Media Lab director in September 2019 after The New Yorker revealed the concealed financial ties.', sources: [{ title: 'Joi Ito, director of MIT Media Lab, resigns over ties to Jeffrey Epstein (MIT Technology Review)', url: 'https://www.technologyreview.com/2019/09/07/133122/joi-ito-mit-media-lab-resignation-jeffrey-epstein-sex-abuse-donation/' }] },
  { name: 'Richard Axel', role: 'Nobel laureate; Columbia University neuroscientist', category: 'named-in-documents', context: 'Correspondence (2010–2019) and an invitation to Epstein’s island appear in the files.' },
  { name: 'Lisa Randall', role: 'Harvard theoretical physicist', category: 'named-in-documents', context: 'Files indicate she met Epstein several times, including a 2014 island visit.' },
  { name: 'Lawrence Krauss', role: 'Theoretical physicist and author', category: 'named-in-documents', context: 'Files show correspondence with Epstein, including a 2017 email seeking advice.' },
  { name: 'Robert Trivers', role: 'Evolutionary biologist', category: 'named-in-documents', context: 'Received research funding from Epstein and introduced others to him.' },
  { name: 'Nathan Wolfe', role: 'Virologist', category: 'named-in-documents', context: 'Named nearly 600 times in the files; corresponded with Epstein (2008–2017).' },
  { name: 'Dean Kamen', role: 'Inventor (Segway)', category: 'named-in-documents', context: 'Emails and photographs reference a 2013 island visit.' },
  { name: 'Stephen Kosslyn', role: 'Psychologist; former Harvard dean', category: 'named-in-documents', context: 'Epstein donated to his Harvard department; files reference visits and proposed projects.' },
  { name: 'David Gelernter', role: 'Yale University computer scientist', category: 'named-in-documents', context: 'Files show correspondence with Epstein (2009–2015).' },
  { name: 'Joscha Bach', role: 'Cognitive scientist', category: 'named-in-documents', context: 'Files indicate his research was subsidized by Epstein, with contact continuing after Epstein’s conviction.' },
  { name: 'Ben Goertzel', role: 'AI researcher; chief scientist at Hanson Robotics', category: 'named-in-documents', context: 'Received grants linked to Epstein’s non-profits (2010–2015).' },
  { name: 'Edward Boyden', role: 'MIT neuroscientist', category: 'named-in-documents', context: 'Referenced as attending a 2015 dinner in Epstein’s emails.' },
  { name: 'Adam Back', role: 'Cryptographer; co-founder of Blockstream', category: 'named-in-documents', context: 'Invited to Epstein’s island in 2014, the year Epstein invested in Blockstream.' },
  { name: 'Jack Horner', role: 'Paleontologist', category: 'named-in-documents', context: 'Visited an Epstein-owned New Mexico property in 2012 and exchanged emails about a research project.' },
  { name: 'Joshua Cooper Ramo', role: 'Author; Kissinger Associates executive', category: 'named-in-documents', context: 'Scheduling documents show more than a dozen meetings with Epstein.' },
  { name: 'Howard Gardner', role: 'Harvard developmental psychologist', category: 'named-in-documents', context: 'Named as a recipient of Epstein research funding; has said he had no knowledge of Epstein’s conduct.' },
  { name: 'Roger Schank', role: 'AI and cognitive-science pioneer (deceased)', category: 'named-in-documents', context: 'Files show he publicly defended Epstein and corresponded with him.' },

  // Culture / media
  { name: 'Woody Allen', role: 'Filmmaker', category: 'named-in-documents', context: 'Named as a townhouse guest who appeared in photographs and a birthday book; he has said he knew nothing of Epstein’s crimes.' },
  { name: 'David Copperfield', role: 'Illusionist', category: 'named-in-documents', context: 'Referenced in phone-message pads, a 2007 email, and a deposition; photographed with Maxwell.' },
  { name: 'David Blaine', role: 'Magician and endurance performer', category: 'named-in-documents', context: 'Files show years-long correspondence and regular dinners with Epstein (2012–2016).' },
  { name: 'Brett Ratner', role: 'Film director and producer', category: 'named-in-documents', context: 'Photographs in the files show him with Epstein.' },
  { name: 'Kevin Spacey', role: 'Actor', category: 'named-in-documents', context: 'Recorded on a 2002 Africa trip aboard Epstein’s plane that also carried Bill Clinton; not accused of wrongdoing in the records.' },
  { name: 'Chris Tucker', role: 'Actor and comedian', category: 'named-in-documents', context: 'Recorded on the 2002 Africa trip aboard Epstein’s plane; appears in photographs. Not accused of wrongdoing.' },
  { name: 'Michael Wolff', role: 'Author and journalist', category: 'named-in-documents', context: 'Files show extended correspondence with Epstein; Wolff has written about their contact.' },
  { name: 'Andres Serrano', role: 'Artist and photographer', category: 'named-in-documents', context: 'Photographed Epstein shortly before his death in 2019.' },
  { name: 'John Brockman', role: 'Founder of Edge Foundation; literary agent', category: 'associate', context: 'Epstein funded approximately 74% of the Edge Foundation budget and was a regular attendee at the annual invitation-only "Billionaires\' Dinner" that Brockman organised for leading scientists and tech executives. Brockman appears in more than 3,300 documents in the released Epstein files.', sources: [{ title: 'How Jeffrey Epstein Bankrolled The Exclusive Edge Foundation And Reaped The Benefits (BuzzFeed News)', url: 'https://www.buzzfeednews.com/article/peteraldhous/jeffrey-epstein-john-brockman-edge-foundation' }] },

  // Legal
  { name: 'Matthew Menchel', role: 'Defense attorney', category: 'legal', context: 'Files reference his role around Epstein’s 2007 plea deal and later correspondence.' },
  { name: 'David Schoen', role: 'Defense attorney', category: 'legal', context: 'Corresponded with Epstein from 2011 until shortly before his death.' },
  { name: 'Paul Tweed', role: 'Defamation lawyer', category: 'legal', context: 'Worked with Epstein on his UK media strategy.' },

  // Additional academics documented in 2025–2026 file releases
  { name: 'Nicholas Christakis', role: 'Yale Sterling Professor of Social and Natural Science; sociologist and physician', category: 'named-in-documents', context: 'Met with Epstein for approximately 90 minutes at his Manhattan townhouse in September 2013 to discuss science and potential lab funding; email correspondence between the two continued through 2016. Yale\'s development office was aware of and supported the 2013 meeting; Epstein did not provide any funding. Christakis has stated he was "appalled by the revelations about Mr. Epstein."', sources: [{ title: 'Nicholas Christakis met and emailed with Epstein about his research (Yale Daily News)', url: 'https://yaledailynews.com/articles/nicholas-christakis-met-and-emailed-with-epstein-about-his-research' }, { title: 'Professors in the Epstein files say they hoped friendship would lead to research funding (Boston Globe)', url: 'https://www.bostonglobe.com/2026/02/13/nation/epstein-files-academics-connection/' }] },

  // Additional figures documented in 2025–2026 file releases
  { name: 'Mohammed bin Salman', aka: ['MBS', 'Crown Prince Mohammed bin Salman'], role: 'Crown Prince and Prime Minister of Saudi Arabia', category: 'official', context: 'Named approximately 97 times in the released files; a DOJ-released photograph appears to show him with Epstein. Records document Epstein flying to Riyadh in 2016 and subsequently describing receiving a tent and carpets as a gift from the Crown Prince.', sources: [{ title: 'Inside Jeffrey Epstein\’s relationship with Saudi Arabia (CBS News)', url: 'https://www.cbsnews.com/news/jeffrey-epstein-saudi-arabia/' }] },
  { name: 'Stephen Hawking', role: 'Theoretical physicist and cosmologist (deceased)', category: 'named-in-documents', context: 'Attended an Epstein-organized scientific conference on Little Saint James island in March 2006; a photograph taken at the event is included in the DOJ-released files. His family has stated that the women pictured with him were caregivers. No wrongdoing is alleged against him.', sources: [{ title: 'Did Stephen Hawking attend an Epstein conference? (Snopes)', url: 'https://www.snopes.com/fact-check/stephen-hawking-jeffrey-epsteins-conference/' }] },
  { name: 'John Brockman', role: 'Literary agent; founder of Edge Foundation', category: 'associate', context: 'Documented emails in the released files show a years-long relationship with Epstein, who was the Edge Foundation\’s principal funder; Brockman facilitated Epstein\’s introductions to leading scientists and hosted annual dinners partly subsidized by Epstein.', sources: [{ title: 'How Epstein Bankrolled the Edge Foundation (BuzzFeed News)', url: 'https://www.buzzfeednews.com/article/peteraldhous/jeffrey-epstein-john-brockman-edge-foundation' }] },
  { name: 'Martha Stewart', role: 'Media personality, author, and lifestyle entrepreneur', category: 'named-in-documents', context: 'Appears approximately 211 times in the files; documented emails include a 2014 request for a seat on Epstein\’s plane to the TED conference and invitations to dinners at his Manhattan townhouse.', sources: [{ title: 'Breaking down boldface names in the Epstein files (CNN)', url: 'https://www.cnn.com/2026/02/03/politics/epstein-files-musk-lutnick-branson-emails' }] },
  { name: 'Katie Couric', role: 'Television journalist and host', category: 'named-in-documents', context: 'Attended a December 2010 dinner at Epstein\’s Manhattan townhouse; an email in the files shows her thanking him for dinner. Couric has acknowledged the attendance and expressed regret about not investigating Epstein\’s background at the time.', sources: [{ title: 'New emails show how Epstein used the media to rehab his reputation (Semafor)', url: 'https://www.semafor.com/article/02/08/2026/new-emails-show-how-epstein-used-the-media-to-rehab-his-reputation' }] },
  { name: 'George Stephanopoulos', role: 'ABC News anchor; former White House Communications Director', category: 'named-in-documents', context: 'Attended a December 2010 dinner hosted by Epstein in honour of Prince Andrew; his attendance is documented in email planning records in the released files. He has publicly called the attendance "a mistake."', sources: [{ title: 'George Stephanopoulos says attending Epstein dinner was a mistake (NTD)', url: 'https://www.ntd.com/abcs-george-stephanopoulos-on-attending-jeffrey-epstein-dinner-it-was-a-mistake_357417.html' }] },
  { name: 'Charlie Rose', role: 'Television journalist and talk-show host', category: 'named-in-documents', context: 'Attended a December 2010 dinner hosted by Epstein in honour of Prince Andrew; his name appears in email records documenting invitation coordination for the event, as revealed in the 2026 file releases.', sources: [{ title: 'New emails show how Epstein used the media to rehab his reputation (Semafor)', url: 'https://www.semafor.com/article/02/08/2026/new-emails-show-how-epstein-used-the-media-to-rehab-his-reputation' }] },
  { name: 'Chelsea Handler', role: 'Comedian, author, and television host', category: 'named-in-documents', context: 'Attended a December 2010 dinner hosted by Epstein in honour of Prince Andrew; her name appears in email records documenting invitation coordination for the event, as revealed in the 2026 file releases.', sources: [{ title: 'New emails show how Epstein used the media to rehab his reputation (Semafor)', url: 'https://www.semafor.com/article/02/08/2026/new-emails-show-how-epstein-used-the-media-to-rehab-his-reputation' }] },
];

function escFm(s: string): string {
  return '"' + String(s).replace(/\\/g, '\\\\').replace(/"/g, '\\"') + '"';
}

function build(p: Person): string {
  const sources = [WIKI, ...(p.sources || [])];
  const seoTitle = `Is ${p.name} in the Epstein Files? — ${p.role}`;
  const seoDesc = `${p.name} (${p.role}) is named in connection with the Jeffrey Epstein files: ${p.context}`.slice(0, 300);
  const shortBio = `${p.name} — ${p.role} — is named in connection with the Jeffrey Epstein files. ${p.context} This profile is auto-generated from public reporting and is pending editorial review; inclusion does not imply guilt or wrongdoing.`;

  const fm: string[] = [];
  fm.push(`name: ${escFm(p.name)}`);
  fm.push(`seoTitle: ${escFm(seoTitle)}`);
  fm.push(`seoDescription: ${escFm(seoDesc)}`);
  if (p.aka && p.aka.length) {
    fm.push('aliases:');
    for (const a of p.aka) fm.push(`  - ${escFm(a)}`);
  } else {
    fm.push('aliases: []');
  }
  fm.push(`role: ${escFm(p.role)}`);
  fm.push(`category: ${p.category}`);
  fm.push(`shortBio: ${escFm(shortBio)}`);
  fm.push('notableConnections:');
  fm.push('  - jeffrey-epstein');
  fm.push('sources:');
  for (const s of sources) {
    fm.push(`  - title: ${escFm(s.title)}`);
    fm.push(`    url: ${escFm(s.url)}`);
  }
  fm.push('sensitive: false');
  fm.push('status: review');
  fm.push('autogenerated: true');

  // Answer-engine (AEO) Q&A body — phrased so search + chatbots quote it cleanly.
  const body = [
    `> **Auto-generated profile pending review.** This entry was compiled from public reporting because ${p.name} is named in connection with the Epstein files. It has not yet been editorially expanded.`,
    '',
    `## Is ${p.name} in the Epstein files?`,
    '',
    `Yes. ${p.name} (${p.role}) is named in connection with the Jeffrey Epstein files. ${p.context}`,
    '',
    `Being named in the files is **not** evidence of any crime or wrongdoing. People appear in these documents in many contexts — correspondence, flight logs, contact books, scheduling, photographs, or passing references. See the sources below for the specific, documented context, and the note at the bottom of this page.`,
    '',
  ].join('\n');

  return `---\n${fm.join('\n')}\n---\n\n${body}`;
}

function main() {
  // Dedup against existing by slug AND by name/alias
  const existingSlugs = new Set(readdirSync(PEOPLE_DIR).filter((f) => f.endsWith('.md')).map((f) => f.replace(/\.md$/, '')));
  const existingNames = new Set<string>();
  for (const f of readdirSync(PEOPLE_DIR).filter((f) => f.endsWith('.md'))) {
    const { frontmatter } = parseFrontmatter(readFileSync(join(PEOPLE_DIR, f), 'utf-8'));
    if (frontmatter.name) existingNames.add(String(frontmatter.name).toLowerCase());
    if (Array.isArray(frontmatter.aliases)) for (const a of frontmatter.aliases) existingNames.add(String(a).toLowerCase());
  }

  let created = 0;
  let skipped = 0;
  for (const p of PEOPLE) {
    const slug = slugify(p.name);
    if (existingSlugs.has(slug) || existingNames.has(p.name.toLowerCase())) {
      skipped++;
      console.log(`  SKIP (exists): ${p.name}`);
      continue;
    }
    const path = join(PEOPLE_DIR, `${slug}.md`);
    if (existsSync(path)) { skipped++; continue; }
    writeFileSync(path, build(p));
    created++;
    console.log(`  + ${slug} (${p.category})`);
  }
  console.log(`\nDone. Created ${created}, skipped ${skipped}. Total curated: ${PEOPLE.length}.`);
}

main();
