/**
 * scaffold-people.ts — auto-grow the people list.
 *
 * Creates thin, review-flagged STUB profiles for individuals who are named in
 * surviving (fact-checked) articles but don't yet have a profile, so that the
 * subsequent cross-link step can link them and the "list" stays comprehensive.
 *
 * Runs AFTER fact-check (so only surviving articles contribute) and BEFORE
 * cross-link (so the new profiles exist when cross-link scans article bodies).
 *
 * Safety: emits MINIMAL, neutral, `status: review` + `autogenerated: true`
 * stubs — never an AI-written biography — to avoid defamation risk. A human
 * reviews and expands them. Idempotent: never recreates or overwrites an
 * existing profile.
 */
import { readFileSync, writeFileSync, readdirSync, existsSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import { parseFrontmatter, loadPeople, slugify } from './lib/pipeline-utils.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const PEOPLE_DIR = join(__dirname, '..', 'src', 'content', 'people');
const ARTICLES_DIR = join(__dirname, '..', 'src', 'content', 'articles');
const RELEVANT_PATH = join(__dirname, 'config', 'relevant.json');

const PER_RUN_CAP = 8;

// Central figures always have curated profiles — never scaffold these.
const UNIVERSAL_SLUGS = new Set(['jeffrey-epstein', 'ghislaine-maxwell']);

// Obvious non-persons / collectives that occasionally slip through extraction.
const STOPLIST = new Set([
  'congress', 'senate', 'house', 'house of representatives', 'doj', 'department of justice',
  'fbi', 'cia', 'gop', 'republicans', 'democrats', 'lawmakers', 'officials', 'white house',
  'supreme court', 'the times', 'new york times', 'wall street journal', 'washington post',
  'the guardian', 'reuters', 'associated press', 'bloomberg', 'fox news', 'jane doe', 'john doe',
  'jeffrey epstein', 'ghislaine maxwell', 'epstein estate', 'southern district', 'maga',
  'trump administration', 'the epstein files', 'epstein files',
]);

const ORG_SUFFIX =
  /\b(inc|llc|ltd|corp|company|foundation|university|college|institute|bank|group|fund|capital|partners|associates|committee|department|agency|bureau|office|news|times|post|journal|press|media|network)\b/i;

function isLikelyPersonName(name: string): boolean {
  const n = name.trim();
  if (n.length < 5 || n.length > 40) return false;
  if (/\d/.test(n)) return false;
  if (ORG_SUFFIX.test(n)) return false;
  const tokens = n.split(/\s+/);
  if (tokens.length < 2 || tokens.length > 4) return false;
  const particles = new Set(['de', 'van', 'von', 'der', 'del', 'la', 'di', 'da', 'bin', 'al', 'the']);
  return tokens.every(
    (t) => particles.has(t.toLowerCase()) || /^[A-Z][A-Za-z.'’-]*$/.test(t),
  );
}

function looksLikeSlug(s: string): boolean {
  return /^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(s);
}

function titleCaseFromSlug(slug: string): string {
  return slug
    .split('-')
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ');
}

function normalizeName(raw: string): string {
  const t = String(raw).trim().replace(/^["']|["']$/g, '');
  if (looksLikeSlug(t) && t.includes('-')) return titleCaseFromSlug(t);
  return t;
}

interface SrcArticle {
  slug: string;
  title: string;
  url: string;
  date: string | null;
}

interface Candidate {
  name: string;
  slug: string;
  articles: Map<string, SrcArticle>;
  tags: Set<string>;
  coExistingSlugs: Set<string>;
  confidence: number;
  newsworthiness: number;
}

/** Best-effort per-name confidence/newsworthiness from the filter output. */
function loadRelevantOverlay(): Map<string, { confidence: number; newsworthiness: number }> {
  const map = new Map<string, { confidence: number; newsworthiness: number }>();
  if (!existsSync(RELEVANT_PATH)) return map;
  try {
    const data = JSON.parse(readFileSync(RELEVANT_PATH, 'utf-8'));
    const entries: any[] = Array.isArray(data) ? data : data.articles || data.relevant || [];
    for (const e of entries) {
      const fr = e.filterResult || e;
      const conf = Number(fr.confidence) || 0;
      const news = Number(fr.newsworthiness) || 0;
      for (const mp of fr.mentionedPeople || []) {
        const key = normalizeName(String(mp)).toLowerCase();
        const cur = map.get(key) || { confidence: 0, newsworthiness: 0 };
        map.set(key, {
          confidence: Math.max(cur.confidence, conf),
          newsworthiness: Math.max(cur.newsworthiness, news),
        });
      }
    }
  } catch {
    /* ignore malformed relevant.json */
  }
  return map;
}

function inferCategory(tags: Set<string>): string {
  const t = [...tags].map((x) => x.toLowerCase());
  const has = (...keys: string[]) => keys.some((k) => t.some((tag) => tag.includes(k)));
  if (has('victim', 'survivor', 'accuser')) return 'victim-survivor';
  if (has('senator', 'congress', 'representative', 'lawmaker', 'official', 'government', 'politician', 'attorney-general', 'white-house'))
    return 'official';
  return 'named-in-documents';
}

function yamlStr(s: string): string {
  return '"' + String(s).replace(/\\/g, '\\\\').replace(/"/g, '\\"') + '"';
}

function buildStub(c: Candidate): string {
  const category = inferCategory(c.tags);
  const sensitive = category === 'victim-survivor';
  const dates = [...c.articles.values()].map((a) => a.date).filter(Boolean) as string[];
  const earliest = dates.sort()[0] || null;
  const sources = [...c.articles.values()]
    .filter((a) => a.url && /^https?:\/\//.test(a.url))
    .slice(0, 5)
    .map((a) => ({ title: a.title || a.slug, url: a.url }));
  const connections = ['jeffrey-epstein', ...[...c.coExistingSlugs].slice(0, 3)];

  const fm: string[] = [];
  fm.push(`name: ${yamlStr(c.name)}`);
  fm.push(`role: ${yamlStr('Named in Epstein-related reporting')}`);
  fm.push(`category: ${category}`);
  fm.push('aliases: []');
  fm.push(
    `shortBio: ${yamlStr(
      `${c.name} was named in news reporting connected to the Jeffrey Epstein case. This profile was auto-generated from coverage and is pending editorial review. Inclusion does not imply guilt or wrongdoing — see the sources below for the specific context.`,
    )}`,
  );
  fm.push('notableConnections:');
  for (const s of connections) fm.push(`  - ${s}`);
  if (earliest) fm.push(`firstMentionedDate: ${earliest}`);
  if (sources.length) {
    fm.push('sources:');
    for (const s of sources) {
      fm.push(`  - title: ${yamlStr(s.title)}`);
      fm.push(`    url: ${yamlStr(s.url)}`);
    }
  } else {
    fm.push('sources: []');
  }
  fm.push(`sensitive: ${sensitive}`);
  fm.push('status: review');
  fm.push('autogenerated: true');
  if (c.confidence) fm.push(`confidence: ${c.confidence}`);

  const coverage =
    [...c.articles.values()]
      .slice(0, 10)
      .map((a) => `- [${a.title || a.slug}](/news/${a.slug}/)`)
      .join('\n') || '_No linked coverage available._';

  const body = [
    `> **Auto-generated profile pending review.** This entry was created automatically because ${c.name} was named in recent coverage of the Epstein files. It has not yet been editorially reviewed or expanded.`,
    '',
    `Inclusion in this list does not imply guilt, wrongdoing, or criminal conduct of any kind. ${c.name} may appear in the files or in coverage only in passing, as part of routine correspondence, or because they are mentioned in news articles connected to the case. See the sources below for the specific nature and context of the connection.`,
    '',
    '## Coverage',
    '',
    coverage,
    '',
  ].join('\n');

  return `---\n${fm.join('\n')}\n---\n\n${body}`;
}

function main() {
  const existing = loadPeople(PEOPLE_DIR);
  const existingSlugs = new Set(existing.map((p) => p.slug));
  const existingNames = new Set<string>();
  for (const p of existing) {
    if (p.name) existingNames.add(p.name.toLowerCase());
    for (const a of p.aliases) if (a) existingNames.add(a.toLowerCase());
  }

  const overlay = loadRelevantOverlay();
  const candidates = new Map<string, Candidate>();

  const articleFiles = readdirSync(ARTICLES_DIR).filter((f) => f.endsWith('.md'));
  console.log(`Scanning ${articleFiles.length} articles for unprofiled named people...`);

  for (const file of articleFiles) {
    const articleSlug = file.replace(/\.md$/, '');
    const content = readFileSync(join(ARTICLES_DIR, file), 'utf-8');
    const { frontmatter } = parseFrontmatter(content);
    const ppl: string[] = Array.isArray(frontmatter.people) ? frontmatter.people : [];
    if (ppl.length === 0) continue;

    const title = String(frontmatter.title || '').replace(/^["']|["']$/g, '');
    const sourceUrl = String(frontmatter.sourceUrl || '').replace(/^["']|["']$/g, '');
    const pubRaw = frontmatter.publishedAt ? String(frontmatter.publishedAt).replace(/^["']|["']$/g, '') : '';
    const pub = pubRaw ? pubRaw.slice(0, 10) : null;
    const tags: string[] = Array.isArray(frontmatter.tags) ? frontmatter.tags : [];

    // Split this article's people into resolved (existing) and unresolved (candidates).
    const resolvedExisting: string[] = [];
    const unresolved: string[] = [];
    for (const entry of ppl) {
      const nm = normalizeName(entry);
      const slug = slugify(nm);
      if (existingSlugs.has(entry) || existingSlugs.has(slug) || existingNames.has(nm.toLowerCase())) {
        resolvedExisting.push(existingSlugs.has(entry) ? entry : slug);
      } else {
        unresolved.push(entry);
      }
    }

    for (const entry of unresolved) {
      const name = normalizeName(entry);
      const slug = slugify(name);
      if (!slug || UNIVERSAL_SLUGS.has(slug)) continue;
      if (STOPLIST.has(name.toLowerCase())) continue;
      if (!isLikelyPersonName(name)) continue;

      let c = candidates.get(slug);
      if (!c) {
        c = {
          name,
          slug,
          articles: new Map(),
          tags: new Set(),
          coExistingSlugs: new Set(),
          confidence: 0,
          newsworthiness: 0,
        };
        const ov = overlay.get(name.toLowerCase());
        if (ov) {
          c.confidence = ov.confidence;
          c.newsworthiness = ov.newsworthiness;
        }
        candidates.set(slug, c);
      }
      c.articles.set(articleSlug, { slug: articleSlug, title, url: sourceUrl, date: pub });
      for (const t of tags) c.tags.add(t);
      for (const rs of resolvedExisting) if (!UNIVERSAL_SLUGS.has(rs)) c.coExistingSlugs.add(rs);
    }
  }

  const list = [...candidates.values()]
    .filter((c) => c.articles.size >= 1 && !existsSync(join(PEOPLE_DIR, `${c.slug}.md`)))
    .sort(
      (a, b) =>
        b.articles.size - a.articles.size ||
        b.confidence - a.confidence ||
        a.name.localeCompare(b.name),
    );

  const selected = list.slice(0, PER_RUN_CAP);
  let created = 0;
  for (const c of selected) {
    const path = join(PEOPLE_DIR, `${c.slug}.md`);
    if (existsSync(path)) continue; // idempotent guard
    writeFileSync(path, buildStub(c));
    created++;
    console.log(`  SCAFFOLDED: ${c.slug} — ${c.articles.size} article(s), conf=${c.confidence || 'n/a'}`);
  }

  const deferred = Math.max(0, list.length - selected.length);
  console.log(
    `\nDone. Scaffolded ${created} new profile(s). ${list.length} candidate(s) found${deferred ? `; ${deferred} deferred by per-run cap (${PER_RUN_CAP})` : ''}.`,
  );
}

main();
